### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by cesarjr**
Hi!

Great job! Your gem is very useful.

If you permit me :-)... I think you could put your blog post in the readme file.

Thank you.

### CODE REVIEW

**Comment by edelpero** [comment]
@cesarjr thank you very much. I'm glad you find it useful.

If you like it would be better if you could add the article to the wiki of the project :smile:.

**Comment by cesarjr** [comment]
Hi!

I'm not sure, but I think I don't have access to create the project wiki.

Thanks.

**Comment by cesarjr** [comment]
Hi!

I updated redme with an example of test using rspec.

Thanks.

**Comment by cesarjr** [comment]
I removed the link like you asked me.

I also checked that you had a readme.rdoc and a readme.md. I think readme.rdoc was not been used, so I deleted it.

About the link: 

I don't know what you think about it, but your blog post gave an excelent compreension about the problem and I only used the gem because of this. 

Think about it fondly. I think it's worth.

Thank you again for your great work!

**Comment by edelpero** [comment]
Could you check why is not letting to automatically merge this pull request @cesarjr?

**Pull request closed without merging**
